---
workflow:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    - if: '$CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS'
      when: never
    - if: '$CI_COMMIT_BRANCH'
    - if: '$CI_COMMIT_TAG'

stages:
  - build
  - test
  - pre_release
  - release
  - deploy

### Build ###

Build Image:
  stage: build
  extends: .build
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    - if: '$CI_COMMIT_BRANCH'

### Test ###

Test:
  stage: test
  extends: .test
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    - if: '$CI_COMMIT_BRANCH'

### Pre Release ###

Prepare release:
  stage: pre_release
  extends: .prepare_release
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      allow_failure: true
    - if: '$CI_COMMIT_BRANCH'

### Release ###

Create Release:
  stage: release
  extends: .create_release
  release:
    tag_name: $CI_COMMIT_TAG
  rules:
    - if: '$CI_COMMIT_TAG'

Tag Image:
  stage: release
  extends: .tag_image
  variables:
    APP_VERSION: $CI_COMMIT_TAG
  rules:
    - if: '$CI_COMMIT_TAG'

### Deploy ###

Deploy Staging:
  stage: deploy
  extends: .deploy_staging
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'

Stop Staging:
  stage: deploy
  extends: .stop_staging
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      allow_failure: true
      when: manual

Deploy Production:
  stage: deploy
  extends: .deploy_production
  variables:
    APP_VERSION: $CI_COMMIT_TAG
  rules:
    - if: '$CI_COMMIT_TAG'
      when: manual
