---
.build:
  stage: build
  tags:
    - docker-build
  variables:
    DOCKER_CONTEXT: .
    DOCKER_IMAGE: $CI_REGISTRY_IMAGE
  before_script:
    - !reference [.docker_login, script]
  script:
    - |-
      if docker pull "$DOCKER_IMAGE:$CI_COMMIT_SHORT_SHA" 2>/dev/null; then
        echo "Image already present in registry, skipping build!"
        exit 0
      fi
    - docker pull "$DOCKER_IMAGE:${CI_COMMIT_BEFORE_SHA:0:8}" 2>/dev/null ||
        docker pull "$DOCKER_IMAGE:latest" 2>/dev/null ||
        true
    - docker build
        --cache-from "$DOCKER_IMAGE:${CI_COMMIT_BEFORE_SHA:0:8}"
        --cache-from "$DOCKER_IMAGE:latest"
        --build-arg BUILD_DATE="$(date -u +'%Y-%m-%dT%H:%M:%SZ')"
        --build-arg VCS_REF="$CI_COMMIT_SHORT_SHA"
        --build-arg VCS_URL="$CI_PROJECT_URL"
        --tag "$DOCKER_IMAGE:$CI_COMMIT_SHORT_SHA" "$DOCKER_CONTEXT"
    - docker push "$DOCKER_IMAGE:$CI_COMMIT_SHORT_SHA"
