---
.build:
  stage: build
  tags:
    - docker-build
  before_script:
    - !reference [.docker_login, script]
  script:
    - |-
      if docker pull "$CI_REGISTRY_IMAGE:$CI_COMMIT_SHA" 2>/dev/null; then
        echo "Image already present in registry, skipping build!"
        exit 0
      fi
    - docker pull "$CI_REGISTRY_IMAGE:$CI_COMMIT_BEFORE_SHA" 2>/dev/null ||
        docker pull "$CI_REGISTRY_IMAGE:latest" 2>/dev/null ||
        true
    - docker build
        --cache-from "$CI_REGISTRY_IMAGE:$CI_COMMIT_BEFORE_SHA"
        --cache-from "$CI_REGISTRY_IMAGE:latest"
        --build-arg BUILD_DATE="$(date -u +'%Y-%m-%dT%H:%M:%SZ')"
        --build-arg VCS_REF="$CI_COMMIT_SHA"
        --build-arg VCS_URL="$CI_PROJECT_URL"
        --tag "$CI_REGISTRY_IMAGE:$CI_COMMIT_SHA" .
    - docker inspect $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA | grep label-schema
    - docker push "$CI_REGISTRY_IMAGE:$CI_COMMIT_SHA"
